name: Test Syncing

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-**"
    branches:
      - master

permissions:
  contents: read

jobs:
  sync:
    runs-on: syncer
    timeout-minutes: 600
    strategy:
      fail-fast: false
      matrix: 
        network: [mainnet, zen, anagami]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Go
        uses: actions/setup-go@v5
      - name: Sync
        run: |
          go run ./internal/cmd/sync/main.go --log.level=debug --network ${{ matrix.network }} --github.ref ${{ github.sha }}